# Site settings
title: Wyatt Graham | Writings and Reviews
email: wagraham87@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog dedicated to theological and social issues, as well as
  book reviews.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wagraham.github.io" # the base hostname & protocol for your site
twitter_username: wagraham
github_username:  wagraham

# Build settings
markdown: kramdown
excerpt_seperator: <!--more-->
