# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Wyatt Graham
tagline:          'Writings & Reviews'
description:      'A blog dedicated to cultural and theological issues, as well as book reviews.  Follow me at <a href="https://twitter.com/wagraham" target="_blank">@wagraham</a>.'
#url:              http://wyattgraham.com
baseurl:          /

author:
  name:           'Wyatt Graham'
  url:            https://twitter.com/wagraham

paginate:         5

# Custom vars
#version:          2.1.0

#github:
  #repo:           https://github.com/poole/hyde
